import { Request, Response } from "express";
import { VulnerabilityModel } from "models/models";
import { errorResponse, successResponse } from "utils/responseFormat";
import { fetchVulnsFromNVD } from "utils/vuln";

export async function get(req: Request, res: Response) {
  const { cpe } = req.query;
  try {
    if (typeof cpe === "string") {
      const data = await fetchVulnsFromNVD(cpe);
      return res.json(successResponse(data, "CVEs fetched successfully"));
    }
  } catch (error) {
    return res.json(errorResponse(`Internal server error: ${error}`));
  }
}

export async function getAll(req: Request, res: Response) {
  try {
    const vulns = await VulnerabilityModel.find();
    return res.json(
      successResponse(vulns, "Vulnerabilities retrieved successfully")
    );
  } catch (error) {
    return res.json(errorResponse(`Internal server error: ${error}`));
  }
}
